[Draft] Adding support for Nautobot 2.0
nautobot/nautobot-plugin-bgp-models pull request #109
Opened 2023-06-27 08:47 UTC by mzbroch

2023-07-03 20:40 UTC, whitej6 requested changes

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/__init__.py
>  except ImportError:
Can we drop the try/except for the inport?

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/api/urls.py
> +from nautobot.core.api.routers import OrderedDefaultRouter
```suggestion
from nautobot.apps.api import OrderedDefaultRouter
```

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/filter_extensions.py
>  class IPAddressFilterExtension(PluginFilterExtension):
```suggestion
class IPAddressFilterExtension(FilterExtension):
```

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/filter_extensions.py
>  class IPAddressFilterExtension(PluginFilterExtension):
Needs to be updated on line 25 as well, can't submit suggestion

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/filters.py
> +)
```suggestion
from nautobot.apps.filters import StatusModelFilterSetMixin, CreatedUpdatedFilterSetMixin, CustomFieldModelFilterSet
from nautobot.extras.filters import RoleModelFilterSetMixin
```

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/forms.py
> +    field_order = ["status", "tag", "status"]
```suggestion
    field_order = ["status", "tag"]
```

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/migrations/0006_auto_20230628_2056.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring,invalid-name
Rename file to non-autogenerated migration

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/models.py
>  from nautobot.core.models.generics import PrimaryModel, OrganizationalModel
Curious if/why we would still need an `OrganizationalModel`

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/tables.py
>  from nautobot.extras.tables import StatusTableMixin
```suggestion
```

2023-07-03 20:40 UTC, whitej6 commented on nautobot_bgp_models/tables.py
>      TagColumn,
```suggestion
    StatusTableMixin,
    TagColumn,
```

2023-07-17 09:12 UTC, mzbroch commented
Updated as per comments and bumped to Nautobot 2 beta-2

2023-07-21 13:24 UTC, glennmatthews reviewed
Sorry for the delay here!

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
Do we not have any uniqueness constraint at all on the `PeerEndpoint` model? If so then `id` is the best we can do here. Should really think about whether it's at all possible to add one though.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
Feels like we *should* have a uniqueness constraint on `Peering` of (endpoint_a, endpoint_z) but the current model design makes that difficult :(. Using the endpoints as the natural-key at least **should** be doable with a custom `natural_key_field_lookups` property implementation that returns `*list(self.endpoints.all())`

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/models.py
Given the current model design, shouldn't there be a `clean()` that throws an exception if `len(self.endpoints.all()) > 2`?

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
Should be able to use something like `[routing_instance, afi_safi, vrf]` if I'm reading `validate_unique` correctly.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/filters.py
> +from nautobot.extras.filters.mixins import RoleModelFilterSetMixin
Would you mind opening an issue or PR to add `RoleModelFilterSetMixin` to `nautobot.apps.filters`? Looks like an oversight.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/filters.py
>      tag = TagFilter()
Should be able to get rid of `tag = TagFilter()` and just include `"tags"` in `Meta.fields` instead.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
Correct to remove this entirely? Or should just the `queryset` be updated to use the generic Role model?

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
Same question here - change queryset instead of deleting?

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
Same question here.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/forms.py
> -        "role",
Why removed? Is this because of #112?

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/navigation.py
> -                            ),
Should the ImportButtons still be present? Not clear why these are removed.

2023-07-21 13:24 UTC, glennmatthews commented on nautobot_bgp_models/templates/nautobot_bgp_models/peergrouptemplate_retrieve.html
> +                            {% include "nautobot_bgp_models/inc/native_property.html" with property=object.description property_type="role" %}
Looks like you removed the `property_type` check from `native_property.html` - and tagging `Description` as `property_type="role"` seems wrong anyway?

2023-08-31 08:36 UTC, mzbroch commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
I will create a separate thread to track this - it really comes down to the network/topology level abstractions (ie. `"to-route-server"` or `pod-spine-A`). Maybe re-introducing `slug`s :) ?

2023-08-31 08:39 UTC, mzbroch commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
Tracked via https://github.com/nautobot/nautobot-plugin-bgp-models/issues/128

2023-08-31 08:41 UTC, mzbroch commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
Tracking separately via https://github.com/nautobot/nautobot-plugin-bgp-models/issues/128

2023-08-31 08:44 UTC, mzbroch commented on nautobot_bgp_models/models.py
Tracking via https://github.com/nautobot/nautobot-plugin-bgp-models/issues/129 - this is for targeted `develop` as of now.

2023-08-31 08:58 UTC, mzbroch commented on nautobot_bgp_models/filters.py
> +from nautobot.extras.filters.mixins import RoleModelFilterSetMixin
Logged in https://github.com/nautobot/nautobot/issues/4363

2023-08-31 09:00 UTC, mzbroch commented on nautobot_bgp_models/filters.py
>      tag = TagFilter()
👍

2023-08-31 09:03 UTC, mzbroch commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
This was resolved

2023-08-31 09:03 UTC, mzbroch commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
This was resolved

2023-08-31 09:03 UTC, mzbroch commented on nautobot_bgp_models/forms.py
> -    role = DynamicModelChoiceField(queryset=models.PeeringRole.objects.all(), required=False)
This was resolved

2023-08-31 09:06 UTC, mzbroch commented on nautobot_bgp_models/forms.py
> -        "role",
Correct - I believe peering role is a composition of natural keys (or roles + identifiers) of two endpoints.
`Role` attribute itself was removed during my open-source refactor, and this was a bug in the form showing it as available.

2023-08-31 09:06 UTC, mzbroch commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]  # TODO: Glenn?
👍

2023-08-31 09:15 UTC, mzbroch commented on nautobot_bgp_models/navigation.py
> -                            ),
Great catch! I removed them when they were unsupported!

2023-08-31 09:25 UTC, mzbroch commented on nautobot_bgp_models/templates/nautobot_bgp_models/peergrouptemplate_retrieve.html
> +                            {% include "nautobot_bgp_models/inc/native_property.html" with property=object.description property_type="role" %}
Seems like a typo introduced in early @whitej6 's branch. Fixed it.

2023-08-31 09:28 UTC, mzbroch commented
@glennmatthews @whitej6 This is now ready to be merged into `next-2.0`.

2023-08-31 12:27 UTC, whitej6 commented on nautobot_bgp_models/migrations/0003_use_upstream_role_part1.py
> +        ("nautobot_bgp_models", "0002_viewsets_migration"),
Needed for safe new install migrations
```suggestion
        ("nautobot_bgp_models", "0002_viewsets_migration"),
        ("extras", "0061_role_and_alter_status"),
```

2023-08-31 12:29 UTC, whitej6 commented on development/nautobot_config.py
>  # RQ_QUEUES is not set here because it just uses the default that gets imported
@mzbroch may be a good time to re-bake the cookie and replace the whole development folder if we haven't done it recently

2023-08-31 12:34 UTC, whitej6 commented on .github/workflows/ci.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11"]
I think we need to confer internally on what we need/should do for the matrix + include. Not a comment requiring changes for merging but to start conversation. 

@bryanculver as we're reviewing options of GHA runners has there been discussions on how we can be the best stewards of CI runtime minutes?

2023-08-31 12:37 UTC, whitej6 commented on docs/requirements.txt
> -mkdocstrings==0.19
@cmsirbu if RTD is using a modern release of pip for build of env we may be able to align everything to pyproject.toml (poetry). Has there been any testing/investigation on this?

Not blocking comment just for discussion

2023-08-31 12:41 UTC, whitej6 commented on nautobot_bgp_models/__init__.py
> +    min_version = "2.0.0b1"
We need to confirm with Core on the go forward for this. I have been told that min/max should move away from hard coding and instead relying on python dependency constraints. I have not seen an update to docs to reflect this, both attrs show as optional with defaults of None in 2.0.0rc2 RTD.

@lampwins @bryanculver for visibility.

2023-08-31 12:44 UTC, whitej6 commented on nautobot_bgp_models/api/filter_backends.py
> +    """
D212 - Need to make sure this pydocstyle configuration is set for all repos. Saw this change and had to go look at the config. Comment for visibility no action for PR.

@cmsirbu @itdependsnetworks for visibility on drift management on other repos.

2023-08-31 12:47 UTC, whitej6 commented on nautobot_bgp_models/api/views.py
> +from nautobot.extras.api.views import NautobotModelViewSet
```suggestion
from nautobot.apps.api import NautobotModelViewSet
```

2023-08-31 12:47 UTC, bryanculver commented on .github/workflows/ci.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11"]
For now it's fine as is. In the future we will be ensuring to test what we must test by rolling out new standards via the cookiecutter template.

2023-08-31 12:52 UTC, bryanculver commented on nautobot_bgp_models/__init__.py
> +    min_version = "2.0.0b1"
@whitej6 you're fairly correct but we're going to deprecate it in 2.X and remove support for it entirely in a future version: https://github.com/nautobot/nautobot/issues/764

2023-08-31 12:53 UTC, whitej6 commented on nautobot_bgp_models/filter_extensions.py
> +from nautobot.apps.filters import MultiValueCharFilter
```suggestion
```

2023-08-31 12:54 UTC, bryanculver commented on nautobot_bgp_models/api/serializers.py
>  from nautobot.core.settings_funcs import is_truthy
Please drop a comment here: https://github.com/nautobot/nautobot/issues/3165

2023-08-31 13:02 UTC, whitej6 commented on nautobot_bgp_models/filters.py
> +# pylint: disable=unsupported-binary-operation
Is this due to the use of `|` in the `Q` filters? Curious if we can `from __future__ import annotations` + comment on why the import is needed (and a different possible inline pylint disable). Or a comment that it will not be required >= py3.10 If my suspicion on why is correct

Only asking because global file disables may be less obvious and possibly when we drop 3.8 & 3.9 support it's no longer needed.

2023-08-31 13:08 UTC, whitej6 commented on nautobot_bgp_models/filters.py
> +    BaseFilterSet, CreatedUpdatedModelFilterSetMixin, CustomFieldModelFilterSetMixin, StatusModelFilterSetMixin
Are we able to just use `NautobotFilterSet`?

2023-08-31 13:09 UTC, whitej6 commented on nautobot_bgp_models/filters.py
> +        fields = ["id", "asn", "status", "tags"]
```suggestion
        fields = models.AutonomousSystem().all_fields
```

@glennmatthews thoughts on moving to this pattern?

2023-08-31 13:11 UTC, whitej6 commented on nautobot_bgp_models/forms.py
> +import nautobot.core.forms as utilities_forms
How much of this is now in `nautobot.apps.forms` and the ones missing we may need to open a PR into core?

2023-08-31 13:17 UTC, whitej6 commented on nautobot_bgp_models/models.py
>  from nautobot.extras.utils import extras_features
```suggestion
from nautobot.apps.models import extras_features
```

2023-08-31 13:21 UTC, whitej6 commented on nautobot_bgp_models/models.py
> +    role = RoleField(blank=True, null=True)
I _think_ based on other conversations we should only use `null=True` for a FK field to align with expected behaviors of REST.

FK not set:
```json
{"role": null}
```

CharField not set should be only `blank=True` if not required
```json
{"some_attr": ""}
```

2023-08-31 13:21 UTC, whitej6 commented on nautobot_bgp_models/models.py
> +    role = RoleField(blank=True, null=True)
May need to be better described as part of dev standards and possibly we explore adding this as a check in pylint nautobot.

@cmsirbu for visibility

2023-08-31 13:23 UTC, whitej6 commented on nautobot_bgp_models/models.py
> +    natural_key_field_names = ["id"]
Any change we are able to implement a unique together constraint instead? I interpreted that we _should_ have a NK lookup & PK lookup, BUT if there's no feasible way to have a unique together constraint this makes sense

2023-08-31 13:24 UTC, glennmatthews commented on nautobot_bgp_models/models.py
> +    role = RoleField(blank=True, null=True)
If a FK field is `null=True` but not `blank=True` then that means it can be set to null via the ORM but a value is required in the UI (and IIRC the REST API as well).

2023-08-31 13:28 UTC, whitej6 commented on nautobot_bgp_models/dolt_compat.py
Do we know if this would still be valid once dolt is back in the picture?

2023-08-31 13:29 UTC, whitej6 commented on pyproject.toml
Can we verify dev dependencies match current standards along with tool config?

Not required for merging but good opportunity to check this.

2023-08-31 13:32 UTC, whitej6 commented on tasks.py
> +            "nautobot_ver": "next",
IMHO this should be pinned to the min version supported to prevent issues with migration dependency resolution. We need to also make this change as part of dev standards in the cookie.

example problem statement
If dev env is running against 2.3.4 nautbot version but minimum is 2.0.0, the migration dependency resolution would be against 2.3.4 and may cause failures on installs <2.3.4 

@cmsirbu & @jvanderaa for visibility

2023-08-31 13:42 UTC, whitej6 commented on nautobot_bgp_models/models.py
> +    role = RoleField(blank=True, null=True)
It may need to be `required=False` on the form & serializer to respect `null=True`

2023-08-31 13:44 UTC, whitej6 commented on nautobot_bgp_models/models.py
> +    role = RoleField(blank=True, null=True)
The dynamic field registration _may_ set `required` based on `blank` and ignore `null` attr.

2023-08-31 18:31 UTC, mzbroch commented
![image](https://github.com/nautobot/nautobot-plugin-bgp-models/assets/16935122/96d8298a-ceeb-42c6-aa01-e82abbdc9492)

2023-09-01 06:51 UTC, mzbroch commented on nautobot_bgp_models/__init__.py
> +    min_version = "2.0.0b1"
This was already fixed

2023-09-01 06:56 UTC, mzbroch commented on tasks.py
> +            "nautobot_ver": "next",
👍

2023-09-01 07:40 UTC, merged